# Generated by Django 5.1.2 on 2025-03-25 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZESFiyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarj_tipi', models.CharField(max_length=100)),
                ('fiyat_metni', models.CharField(max_length=50)),
                ('fiyat_degeri', models.FloatField()),
                ('eklenme_tarihi', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ZES Fiyat',
                'verbose_name_plural': 'ZES Fiyatları',
            },
        ),
        migrations.CreateModel(
            name='ZESFiyatGecmisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarj_tipi', models.CharField(max_length=100)),
                ('eski_fiyat', models.CharField(max_length=50)),
                ('yeni_fiyat', models.CharField(max_length=50)),
                ('eski_fiyat_degeri', models.FloatField()),
                ('yeni_fiyat_degeri', models.FloatField()),
                ('degisim_tarihi', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ZES Fiyat Geçmişi',
                'verbose_name_plural': 'ZES Fiyat Geçmişleri',
            },
        ),
    ]
