# Generated by Django 5.1.2 on 2025-03-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarjucret', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrugoFiyat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarj_tipi', models.CharField(max_length=100)),
                ('fiyat_metni', models.CharField(max_length=50)),
                ('fiyat_degeri', models.FloatField()),
                ('eklenme_tarihi', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Trugo Fiyat',
                'verbose_name_plural': 'Trugo Fiyatları',
            },
        ),
        migrations.CreateModel(
            name='TrugoFiyatGecmisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sarj_tipi', models.CharField(max_length=100)),
                ('eski_fiyat', models.CharField(max_length=50)),
                ('yeni_fiyat', models.CharField(max_length=50)),
                ('eski_fiyat_degeri', models.FloatField()),
                ('yeni_fiyat_degeri', models.FloatField()),
                ('degisim_tarihi', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Trugo Fiyat Geçmişi',
                'verbose_name_plural': 'Trugo Fiyat Geçmişleri',
            },
        ),
    ]
