# Generated by Django 5.1.2 on 2025-05-22 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarjucret', '0003_esarjfiyat_esarjfiyatgecmisi_voltrunfiyat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SarjGecmisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arac', models.CharField(max_length=150)),
                ('arac_kwh', models.FloatField()),
                ('firma', models.CharField(max_length=50)),
                ('baslangic_sarj', models.PositiveSmallIntegerField()),
                ('varis_sarj', models.PositiveSmallIntegerField()),
                ('doldurulan_enerji', models.FloatField()),
                ('toplam_ucret', models.FloatField()),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Şarj Geçmişi',
                'verbose_name_plural': 'Şarj Geçmişleri',
            },
        ),
    ]
